services:
  postgres:
    image: postgres:16
    container_name: tournament_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tournament_db
    ports:
      - "5432:5432"
    volumes:
      - tournament_pgdata:/var/lib/postgresql/data

volumes:
  tournament_pgdata:
